[package]
name = "microsoft_speech"
version = "0.1.5"
authors = ["luyi <luyi@newtranx.com>"]

[dependencies]
log = "0.4.3"
env_logger = "0.5"
failure = "0.1.3"
failure_derive = "0.1.3"
tokio = "0.1.11"
futures = "*"
enum_primitive = "0.1.1"
num = "0.2.0"
